package view;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Chest;
import model.Game;

public class Game_window extends javax.swing.JFrame {

    Game game = new Game();
    Chest[] chests;
    JButton[] chest_buttons;
    boolean chances = true;
    
    public Game_window() {
        initComponents();
        
        chest_buttons = make_chests();
//        for (int x = 0; x < chest_buttons.length; x++)
//        {
//            System.out.println(chest_buttons[x]);
//        }
    }
    
    private JButton[] make_chests()
    {
        Chest[] chests = game.getChests();
        chests_panel.removeAll();
        JButton[] chest_buttons = new JButton[chests.length];
        for (int x = 0; x < chests.length; x++)
        {
            //panel
            JPanel chest_panel = new JPanel();
            chest_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, chests[x].getName(), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
            chest_panel.setLayout(new java.awt.GridLayout());
            //button
            JButton chest = new JButton();
            //img
            ImageIcon img_raw = new ImageIcon(this.getClass().getResource(chests[x].getMaterial_image_path()));
            ImageIcon img = new ImageIcon(img_raw.getImage().getScaledInstance(150, 100, Image.SCALE_DEFAULT));
            chest.setIcon(img);
            //text
            chest.setText(chests[x].getRiddle());
            chest.setHorizontalTextPosition(JButton.CENTER);
            chest.setVerticalTextPosition(JButton.CENTER);
            chest.setForeground(Color.BLACK);
            //action
            int chest_num = x;
            chest.addActionListener((java.awt.event.ActionEvent evt) -> {
                guess_chest(evt, chest_num);
            });
            //add
            chest_panel.add(chest);
            chest_buttons[x] = chest;
            chests_panel.add(chest_panel);
        }
        return chest_buttons;
    }
    
    public void guess_chest(java.awt.event.ActionEvent evt, int chest_num)
    {
        chances = chances_bt.isSelected();
        chances_bt.setEnabled(false);
        if(game.guess(chest_num))
            good_chest();
        else
            bad_chest(evt);
    }
    
    public void good_chest()
    {
        int result = JOptionPane.showConfirmDialog(this, "Megtaláltad a kincset" + (chances ? (" " + game.getAttempts() +" próbálkozásból") : "") + ". Kilépsz?", "Nyertél!", JOptionPane.YES_NO_OPTION);
        if(JOptionPane.YES_OPTION == result)
            dispose();
        else
            for (JButton chest : chest_buttons)
            {
                chest.setEnabled(false);
            }
//        game.add_chest(new Chest("láda","hehe"));
//        make_chests();
        
    }
    
    public void bad_chest(java.awt.event.ActionEvent evt)
    {
        JOptionPane.showMessageDialog(this, "Ez a láda üres volt.", "Vesztettél!", JOptionPane.ERROR_MESSAGE);
        if(!chances)
            dispose();
        else
            ((JButton)(evt.getSource())).setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        chances_bt = new javax.swing.JCheckBox();
        chests_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Találóskérdés");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(750, 500));

        chances_bt.setText("Több próbálkozás: ");
        chances_bt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chances_bt.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        chests_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Csak az eggyik láda mond igazat.", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        chests_panel.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chests_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chances_bt, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addContainerGap())
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chances_bt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chests_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chances_bt;
    private javax.swing.JPanel chests_panel;
    private javax.swing.JPanel main_panel;
    // End of variables declaration//GEN-END:variables
}
